"""baseline: users table

Revision ID: 0001
Revises:
Create Date: Phase 4

Hand-written (not autogenerated) to exactly match the `users` table already
bootstrapped by database/schema.sql in Phase 1's docker-entrypoint-initdb.d
- this is the standard approach for a first migration against a schema
that already exists via a bootstrap script: it establishes Alembic's
baseline without trying to "recreate" a table that's already there in
every environment that ran the Phase 1 bootstrap.

From this migration onward, schema changes should go through
`alembic revision --autogenerate`, run against the real running Postgres,
NOT further hand-edits to schema.sql.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # checkfirst=True: safe to run even in an environment where Phase 1's
    # schema.sql already created this table (local dev via
    # docker-entrypoint-initdb.d) - it won't error on "already exists".
    # Fresh environments (e.g. a CI database with no bootstrap script) get
    # the table created here for the first time.
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("phone_number", sa.String(20), nullable=False, unique=True),
        sa.Column("display_name", sa.String(100), nullable=False),
        sa.Column(
            "preferred_language", sa.String(10), nullable=False, server_default="en"
        ),
        sa.Column("password_hash", sa.String(255), nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        if_not_exists=True,
    )
    op.create_index(
        "idx_users_phone_number", "users", ["phone_number"], if_not_exists=True
    )


def downgrade() -> None:
    op.drop_index("idx_users_phone_number", table_name="users")
    op.drop_table("users")
